version: "3.8"

services:
  refprop:
    build: .
    container_name: refprop-app
    ports:
      - "5051:5000"
    environment:
      - LD_LIBRARY_PATH=/app
      - REFPROP_ROOT=/app
      - PYTHONPATH=/app
      - REFPROP_MAX_PROCESSES=4  # Default max processes to use
    volumes:
      - ./API:/app/API
    restart: unless-stopped